
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class AddPatients extends javax.swing.JFrame {

    /**
     * Creates new form AddPatients
     */
    public AddPatients() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(600, 300));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD PATIENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 70));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 710, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Patient ID ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Father Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Date Of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Mobile No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 20));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 140, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 140, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 140, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 140, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectr Gender", "Male", "Female", "Others" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 140, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 700, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update details.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit application.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Stock");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Hospital Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Blood Group");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("City");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Complete Address");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 160, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 160, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "AB+", "AB-", "B+", "B-", "O+", "O-" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 160, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 160, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 160, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 0, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 700, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image(1).png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blooddonation","bfam","bfam@123");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select patientId from patients");
            if(rs.last())
            {
                int id = rs.getInt(1);
                id++;
                String str = String.valueOf(id);
            
             jLabel16.setText(str);
            }
            else
            {
                jLabel16.setText("1");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    // TODO add your handling code here:
                  
        if(isEmptyData())
        {
           
             int patientId=Integer.parseInt(jLabel16.getText());
                    String fname = jTextField2.getText();
                    String lname = jTextField3.getText();
                    String fathername = jTextField4.getText();
                    String dob = jTextField5.getText();
                    String mobileNumber = jTextField6.getText();
                    String gender = jComboBox1.getSelectedItem().toString();
                    String units = jTextField7.getText();
                    String hname = jTextField8.getText();
                    String bloodg = jComboBox2.getSelectedItem().toString();
                    String city = jTextField9.getText();
                    String address = jTextArea1.getText();
                    
                    try{
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blooddonation","bfam","bfam@123");
                        
                        Statement st = con.createStatement();
                        String sql="insert into patients values('"+ patientId+"','"+fname+"','"+lname+"','"+fathername+"','"+dob+"','"+mobileNumber+"','"+gender+"','"+units+"','"+
                                hname+"','"+bloodg+"','"+city+"','"+address+"')";
                        st.executeUpdate(sql);
                        ResultSet rs =st.executeQuery("select * from stocks");
                        if(rs.last())
                        {
                            int a=rs.getInt("A_Pov");
                            int aa=rs.getInt("A_Neg");
                            int b=rs.getInt("B_Pov");
                            int bb=rs.getInt("B_Neg");
                            int ab=rs.getInt("AB_Pov");
                            int abb=rs.getInt("AB_Neg");
                            int o=rs.getInt("O_Pov");
                            int oo=rs.getInt("O_Neg");
                            
                            if(bloodg.equals("A+")){
                                
                                a=a-Integer.parseInt(units);
                                String sql1="update stocks set A_Pov ='"+a+"' where id=1";
                                st.execute(sql1);
                            }
                            else  if(bloodg.equals("A-")){
                                aa=aa-Integer.parseInt(units);
                                String sql1="update stocks set A_Neg ='"+aa+"' where id=1";
                                st.execute(sql1);
                            }
                            else  if(bloodg.equals("B+")){
                                b=b-Integer.parseInt(units);
                                String sql1="update stocks set B_Pov ='"+b+"' where id=1";
                                st.execute(sql1);
                            }
                            else  if(bloodg.equals("B-")){
                                bb=bb-Integer.parseInt(units);
                                String sql1="update stocks set B_Neg='"+bb+"' where id=)1";
                                st.execute(sql1);
                            }
                            else  if(bloodg.equals("AB+")){
                                ab=ab-Integer.parseInt(units);
                                String sql1="update stocks set AB_Pov='"+ab+"' where id=1";
                                st.execute(sql1);
                            }
                            else  if(bloodg.equals("AB-")){
                                abb=abb-Integer.parseInt(units);
                                String sql1="update stocks set AB_Neg='"+abb+"' where id=1";
                                st.execute(sql1);
                            }
                            else  if(bloodg.equals("O+")){
                                o=o-Integer.parseInt(units);
                                String sql1="update stocks set O_Pov='"+o+"' where id=1";
                                st.execute(sql1);
                            }
                            else  if(bloodg.equals("O+")){
                                oo=oo-Integer.parseInt(units);
                                String sql1="update stocks set O_Neg='"+oo+"' where id=1";
                                st.execute(sql1);
                            }
                            JOptionPane.showMessageDialog(null, "Successfully saved");
                            
                            
                        }
                        
                        setVisible(false);
                        new AddPatients().setVisible(true);
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                        
                    }
                
            
        }
        
            
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
   /*boolean isAvailable() throws Exception
    {
        String bg=jComboBox2.getSelectedItem().toString();
        int unit=Integer.parseInt(jTextField7.getText());
        
      
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blooddonation","bfam","bfam@123");
             Statement st = con.createStatement();
             ResultSet rs =st.executeQuery("select * from stocks where id=1");
             int a=rs.getInt("A_Pov");
             int aa=rs.getInt("A_Neg");
             int b=rs.getInt("B_Pov");
             int bb=rs.getInt("B_Neg");
             int ab=rs.getInt("AB_Pov");
             int abb=rs.getInt("AB_Neg");
             int o=rs.getInt("O_Pov");
             int oo=rs.getInt("O_Neg");
             
             if(unit<=a && bg.equals("A+"))
                 return true;
             else if(unit<=aa && bg.equals("A-"))
                 return true;
             else if(unit<=b && bg.equals("B+"))
                 return true;
             else if(unit<=bb && bg.equals("B-"))
                 return true;
             else  if(unit<=ab && bg.equals("AB+"))
                 return true;
             else if(unit<=abb && bg.equals("AB-"))
                 return true;
             else if(unit<=o && bg.equals("O+"))
                 return true;
             else if(unit<=oo && bg.equals("O-"))
                 return true;
             
             
             JOptionPane.showMessageDialog(null,"Blood is Not Available");
             return true;
    }*/
             
            
            
             
              
        
    
    boolean isEmptyData()
    {
        if(jTextField2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"First Name is Mandetory");
            return false;
        }
        if(jTextField3.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Last Name is Mandetory");
            return false;
           
        }
        if(jTextField4.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Father Name is Mandetory");
            return false;
        }
        if(jTextField5.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Date of Birth  is Mandetory");
            return false;
        }
        if(jTextField6.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Mobile Number is Mandetory");
            return false;
        }
        if(jComboBox1.getSelectedItem().toString().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Selecet Gender");
            return false;
        }
        if(jTextField7.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter the Stock Unit");
            return false;
        }
        if(jTextField8.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Hospital Name is Mandetory");
            return false;
        }
        if(jComboBox2.getSelectedItem().toString().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Select Blood Group");
            return false;
            
        }
        if(jTextField9.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"City Name is Mandetory");
            return false;
        }
        if(jTextArea1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Complete Address");
            return false;
        }
       
        return true;
    }
        
        
    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here 
       
        
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             setVisible(false);
        new AddPatients().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
